"use strict";
var __cov_yJt6pbNaRNLvIwOUh6UXAA = (Function('return this'))();
if (!__cov_yJt6pbNaRNLvIwOUh6UXAA.$$cov_1537032008355$$) { __cov_yJt6pbNaRNLvIwOUh6UXAA.$$cov_1537032008355$$ = {}; }
__cov_yJt6pbNaRNLvIwOUh6UXAA = __cov_yJt6pbNaRNLvIwOUh6UXAA.$$cov_1537032008355$$;
if (!(__cov_yJt6pbNaRNLvIwOUh6UXAA['/mnt/d/dmr/dmr-pipeline/dist/test/test-lines.js'])) {
   __cov_yJt6pbNaRNLvIwOUh6UXAA['/mnt/d/dmr/dmr-pipeline/dist/test/test-lines.js'] = {"path":"/mnt/d/dmr/dmr-pipeline/dist/test/test-lines.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":0,"16":0},"b":{},"f":{},"fnMap":{},"statementMap":{"1":{"start":{"line":2,"column":0},"end":{"line":2,"column":62}},"2":{"start":{"line":3,"column":0},"end":{"line":3,"column":25}},"3":{"start":{"line":4,"column":0},"end":{"line":4,"column":29}},"4":{"start":{"line":5,"column":0},"end":{"line":5,"column":38}},"5":{"start":{"line":6,"column":0},"end":{"line":24,"column":3}},"6":{"start":{"line":7,"column":4},"end":{"line":23,"column":7}},"7":{"start":{"line":8,"column":8},"end":{"line":8,"column":90}},"8":{"start":{"line":9,"column":8},"end":{"line":9,"column":22}},"9":{"start":{"line":10,"column":8},"end":{"line":13,"column":11}},"10":{"start":{"line":11,"column":12},"end":{"line":11,"column":20}},"11":{"start":{"line":12,"column":12},"end":{"line":12,"column":31}},"12":{"start":{"line":14,"column":8},"end":{"line":22,"column":11}},"13":{"start":{"line":15,"column":12},"end":{"line":20,"column":15}},"14":{"start":{"line":16,"column":16},"end":{"line":16,"column":55}},"15":{"start":{"line":17,"column":16},"end":{"line":17,"column":26}},"16":{"start":{"line":19,"column":16},"end":{"line":19,"column":28}}},"branchMap":{}};
}
__cov_yJt6pbNaRNLvIwOUh6UXAA = __cov_yJt6pbNaRNLvIwOUh6UXAA['/mnt/d/dmr/dmr-pipeline/dist/test/test-lines.js'];
__cov_yJt6pbNaRNLvIwOUh6UXAA.s['1']++;Object.defineProperty(exports,'__esModule',{value:true});__cov_yJt6pbNaRNLvIwOUh6UXAA.s['2']++;const fs=require('fs');__cov_yJt6pbNaRNLvIwOUh6UXAA.s['3']++;const path=require('path');__cov_yJt6pbNaRNLvIwOUh6UXAA.s['4']++;const line_1=require('../src/line');__cov_yJt6pbNaRNLvIwOUh6UXAA.s['5']++;describe('Copy File By Using SourceFile',()=>{__cov_yJt6pbNaRNLvIwOUh6UXAA.s['6']++;it('read 5 lines form lines-5.log',()=>{__cov_yJt6pbNaRNLvIwOUh6UXAA.s['7']++;let reader=fs.createReadStream(path.resolve(__dirname,'./assets/lines-5.log'));__cov_yJt6pbNaRNLvIwOUh6UXAA.s['8']++;let lines=0;__cov_yJt6pbNaRNLvIwOUh6UXAA.s['9']++;let out=reader.pipe(new line_1.default()).on('data',chunk=>{__cov_yJt6pbNaRNLvIwOUh6UXAA.s['10']++;lines++;__cov_yJt6pbNaRNLvIwOUh6UXAA.s['11']++;console.log(chunk);});__cov_yJt6pbNaRNLvIwOUh6UXAA.s['12']++;return new Promise((resolve,reject)=>{__cov_yJt6pbNaRNLvIwOUh6UXAA.s['13']++;out.on('end',()=>{__cov_yJt6pbNaRNLvIwOUh6UXAA.s['14']++;console.log(`End with ${lines} lines`);__cov_yJt6pbNaRNLvIwOUh6UXAA.s['15']++;resolve();}).on('error',err=>{__cov_yJt6pbNaRNLvIwOUh6UXAA.s['16']++;reject(err);});;});});});
